### PR TITLE
Feature/db helpers and update schema

### PR DESCRIPTION
**Pull request by lighthurst**
Hi @justuskw, Please review this pull request. Thank you.

https://trello.com/c/fR3ujw7N/13-refactor-schema-with-isavail-column-for-nights-table-s
https://trello.com/c/0lkTbB5o/8-implement-helper-functions-for-server-m
https://trello.com/c/JvkYteWX/11-install-server-dependencies-xs

### CODE REVIEW

**Review by justuskw — APPROVED** [review]
I tried my best to find something that could be improved, but I couldn't. Good work, this code looks really good.

**Comment by lighthurst** [comment]
Thanks for the comment and the quick turnaround, Justus.

**Comment by lighthurst** [comment]
Hi @justuskw. For some reason even after someone has approved a PR, merging is still blocked because no group member has write access. Please change the member permission levels for everyone so we don't have to continue w/ admin override pull request merges w/o official review. Thanks.

**Comment by justuskw** [comment]
Aaron,

I was wondering what was going on there so thanks for pointing this out. I
changed the member permissions so you should be able to approve PR's now.
Let me know if it still doesn't work.

Best,
Justus

**Pull request merged**
